import React from "react";
import { Box, Container } from "@mui/material";
import TopTitle from "../components/TopTitle";
import ALCList from "../components/ALCList";

const alcData = [
  {
    id: 1,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fprize%2Fpr1.jpg?alt=media&token=a270b6f1-ca6c-412f-a303-8c268166c70f",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faTrophy",
    alcTitle: "국경 없는 과학자 기술자 회장상",
    alcSubTitle: "제 10회 소외된 90%를 위한 창의설계 경진대회",
    alcOrganizer: "과학기술정보통신부",
    alcDate: "MAY 25, 2018",
    alcLecSite: "http://www.stiweb.org/",
    alcSite: "",
    alcGithub: "https://github.com/ddo0ii/capstone",
    alcBlog: "",
    alcYouTube: "https://youtu.be/5CEzAd3kDtg",
    alcDeTitle1: "LANGUAGE & TOOL",
    alcDeContent1_1: "PWA",
    alcDeContent1_2: "Node.js",
    alcDeContent1_3: "MongoDB",
    alcDeContent1_4: "",
    alcDeTitle2: "INDUSTRY",
    alcDeContent2: "Developer 3",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "청각장애인은 물론 비장애인도 카페에서 음료 제조의 완료 알림을 받을 수 있고, 카페 매장 측은 마케팅 플랫폼으로 활용할 수 있는 시스템을 개발하였다.",
    alcPrototypeVideo: "https://www.youtube.com/embed/5CEzAd3kDtg",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/project%2Fweb%2Flisten%2Flisten1.jpg?alt=media&token=3fe74a94-bbab-45b1-9a36-b2f3d7093a8b",
    alcPrototype2:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fprize%2Fpr1.jpg?alt=media&token=a270b6f1-ca6c-412f-a303-8c268166c70f",
  },
  {
    id: 2,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Fliceip1.jpg?alt=media&token=c84d4bbb-9678-46be-9b8e-773029803076",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "정보처리기사",
    alcSubTitle: "",
    alcOrganizer: "한국산업인력공단",
    alcDate: "AUGUST 20, 2021",
    alcLecSite: "https://www.hrdkorea.or.kr/",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Fliceip3.jpg?alt=media&token=66536971-5316-434e-a6ed-6f7225434ed3",
    alcPrototype2: "",
  },
  {
    id: 3,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Fliceip1.jpg?alt=media&token=c84d4bbb-9678-46be-9b8e-773029803076",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "정보처리산업기사",
    alcSubTitle: "",
    alcOrganizer: "한국산업인력공단",
    alcDate: "NOVEMBER 12, 2020",
    alcLecSite: "https://www.hrdkorea.or.kr/",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Fliceip2.jpg?alt=media&token=f69b4133-1a79-4c6e-9c0f-624acd7c0fb2",
    alcPrototype2: "",
  },
  {
    id: 4,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Flicdb1.jpg?alt=media&token=3656f47d-a2e0-4da3-9313-43f6b07443b3",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "SQL 개발자",
    alcSubTitle: "SQLD",
    alcOrganizer: "데이터자격검정",
    alcDate: "JUNE 24, 2022",
    alcLecSite: "https://www.dataq.or.kr/www/main.do",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Flicdb2.jpg?alt=media&token=ba1bc354-60d6-473c-aaa1-7fd39e700fdd",
    alcPrototype2: "",
  },
  {
    id: 5,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Flico1.jpg?alt=media&token=b726595a-1e5b-4c7f-ad8a-63dafe83af21",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "OPIc",
    alcSubTitle: "Intermediate Mid 2",
    alcOrganizer: "MultiCampus",
    alcDate: "DECEMBER 28, 2019",
    alcLecSite: "https://m.opic.or.kr/opics/jsp/senior/indexMobile.jsp",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Flico2.jpg?alt=media&token=960adbfb-00c0-4096-96b1-e2a87d9a6dfb",
    alcPrototype2: "",
  },
  {
    id: 6,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Fliccu1.jpg?alt=media&token=36b8c2b4-5e31-4e51-b8d6-e1df795abe01",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "컴퓨터활용능력",
    alcSubTitle: "2급",
    alcOrganizer: "대한상공회의소",
    alcDate: "AUGUST 2019",
    alcLecSite: "http://www.korcham.net/nCham/Service/Main/appl/Main.asp",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Fliccu2.jpg?alt=media&token=704f9081-b0a2-49fb-9d2b-6f75145786ba",
    alcPrototype2: "",
  },
  {
    id: 7,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Flicdr2.jpg?alt=media&token=d362a39c-a829-40cf-b2a5-ff32dd5bc7bd",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "자동차 운전면허",
    alcSubTitle: "1종 보통",
    alcOrganizer: "경찰청(운전면허시험관리단)",
    alcDate: "JANUARY 5, 2015",
    alcLecSite: "https://www.safedriving.or.kr/main.do",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Flicense%2Flicdr2.jpg?alt=media&token=1d0b8119-6b8f-4d8f-9b76-5613223c74a8",
    alcPrototype2: "",
  },
  {
    id: 8,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertljh1.jpg?alt=media&token=9d721531-8917-4b51-8533-110c6f1e721f",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "한입 크기로 잘라 먹는 리액트",
    alcSubTitle: "",
    alcOrganizer: "Inflearn",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite:
      "https://www.inflearn.com/course/%ED%95%9C%EC%9E%85-%EB%A6%AC%EC%95%A1%ED%8A%B8/dashboard",
    alcSite: "",
    alcGithub:
      "https://github.com/ddo0ii/inflearn_react/tree/main/emotion-diary",
    alcBlog:
      "https://ddo-development.tistory.com/category/React/%ED%95%9C%EC%9E%85%20%ED%81%AC%EA%B8%B0%EB%A1%9C%20%EC%9E%98%EB%9D%BC%20%EB%A8%B9%EB%8A%94%20%EB%A6%AC%EC%95%A1%ED%8A%B8%28React.js%29",
    alcYouTube: "https://youtu.be/hE4qm1l6Da4",
    alcDeTitle1: "LANGUAGE & TOOL",
    alcDeContent1_1: "React.js",
    alcDeContent1_2: "JavaScript",
    alcDeContent1_3: "Node.js",
    alcDeContent1_4: "Firebase",
    alcDeTitle2: "TRAINING TIME",
    alcDeContent2: "16 Hours 57 Minutes",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "Inflearn의 '한입 크기로 잘라 먹는 리액트(React.js) : 기초부터 실전까지'를 수강하며 JavaScript와 React의 기초적인 개념을 Blog에 기록하며 학습하였다. 최종적으로 React.js를 이용하여 감정일기장을 제작하고 Firebase를 이용하여 프로젝트를 배포하였다.",
    alcPrototypeVideo: "https://www.youtube.com/embed/hE4qm1l6Da4",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/project%2Fweb%2Fdiary%2Fdiary1_s.png?alt=media&token=16957c73-9239-4021-9b64-cb7cf4598cf2",
    alcPrototype2: "",
  },
  {
    id: 9,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertt1.jpg?alt=media&token=0d03c150-96c3-4f1d-b14d-c96ff77d2b44",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "트위터 클론코딩",
    alcSubTitle: "",
    alcOrganizer: "Nomad Coders",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://nomadcoders.co/nwitter",
    alcSite: "https://ddo0ii.github.io/Twitter_React_NomadCoders",
    alcGithub: "https://github.com/ddo0ii/Twitter_React_NomadCoders",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "LANGUAGE & TOOL",
    alcDeContent1_1: "React.js",
    alcDeContent1_2: "JavaScript",
    alcDeContent1_3: "Node.js",
    alcDeContent1_4: "Firebase",
    alcDeTitle2: "TOOL",
    alcDeContent2:
      "Firebase, Cloud Firestore, NoSQL Realtime, Query, Filter, Firebase Authentication, Google Cloud Storage",
    alcDeTitle3: "FUNCTION",
    alcDeContent3:
      "Email, Google, Github, Social Authentication, Tweet CRUD, Protected Pages, Profile Page, File Upload, Deploy, API Key Security",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "Nomad Coders의 '트위터 클론코딩'를 수강하였다. 최종적으로 React.js와 Firebase를 이용하여 백엔드 코딩없이 인증 및 리얼타임 DB를 구현하여 로그인, 트윗작성, 수정 삭제 등의 기본적인 트위터 웹 페이지를 제작하고 Github를 이용하여 프로젝트를 배포하였다.",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertt1.jpg?alt=media&token=0d03c150-96c3-4f1d-b14d-c96ff77d2b44",
    alcPrototype2: "",
  },
  {
    id: 10,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertnw1.jpg?alt=media&token=6cc9257b-621a-424f-8a38-b8a81a798944",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "ReactJS로 영화 웹 서비스 만들기",
    alcSubTitle: "",
    alcOrganizer: "Nomad Coders",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://nomadcoders.co/react-for-beginners",
    alcSite: "https://ddo0ii.github.io/NomadCoders_React",
    alcGithub:
      "https://github.com/ddo0ii/NomadCoders_React/tree/main/react-for-begginners",
    alcBlog:
      "https://ddo-development.tistory.com/category/React/ReactJS%EB%A1%9C%20%EC%98%81%ED%99%94%20%EC%9B%B9%20%EC%84%9C%EB%B9%84%EC%8A%A4%20%EB%A7%8C%EB%93%A4%EA%B8%B0",
    alcYouTube: "",
    alcDeTitle1: "LANGUAGE & TOOL",
    alcDeContent1_1: "React.js",
    alcDeContent1_2: "Node.js",
    alcDeContent1_3: "CSS",
    alcDeContent1_4: "",
    alcDeTitle2: "FUNCTION",
    alcDeContent2:
      "JSX, State, Props, Class Components, Data Fetching, Routing",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "Nomad Coders의 'ReactJS로 영화 웹 서비스 만들기'를 수강하여 React의 기초적인 개념을 Blog에 기록하며 학습하였다. 최종적으로 React.js를 이용하여 영화 웹 서비스 페이지를 제작하고 Github를 이용하여 프로젝트를 배포하였다.",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertnw1.jpg?alt=media&token=6cc9257b-621a-424f-8a38-b8a81a798944",
    alcPrototype2: "",
  },
  {
    id: 11,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertwiset1.jpg?alt=media&token=5bf77b01-a460-4808-b519-6b123aac4b30",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[직딩잇템]처음 시작하는 파이썬, 구조를 학습하라",
    alcSubTitle: "",
    alcOrganizer: "WISET_멀티캠퍼스",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://www.multicampus.com/kr/index.html",
    alcSite: "",
    alcGithub: "",
    alcBlog:
      "https://ddo0ii.notion.site/ddo0ii/Wiset-6c352eb74aab43129dcff5fa6bd0537a",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertps2.jpg?alt=media&token=d07f377f-81b1-4957-b348-fb1995c8f5e4",
    alcPrototype2:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertps1.jpg?alt=media&token=be09a761-b56f-42a7-872f-085c0221c2bc",
  },
  {
    id: 12,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertwiset1.jpg?alt=media&token=5bf77b01-a460-4808-b519-6b123aac4b30",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[직딩잇템]처음 시작하는 파이썬, 문법부터 시작하라",
    alcSubTitle: "",
    alcOrganizer: "WISET_멀티캠퍼스",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://www.multicampus.com/kr/index.html",
    alcSite: "",
    alcGithub: "",
    alcBlog:
      "https://ddo0ii.notion.site/ddo0ii/Wiset-6c352eb74aab43129dcff5fa6bd0537a",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertpg2.jpg?alt=media&token=cdbed099-077f-42de-82c6-6c5566a999c9",
    alcPrototype2:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertpg1.jpg?alt=media&token=109d9a49-af96-4809-8e6e-fee73c697b0a",
  },
  {
    id: 13,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertwiset1.jpg?alt=media&token=5bf77b01-a460-4808-b519-6b123aac4b30",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[큐레이팅#]누구나 DO IT! 쉽게 시작하는 AI&프로그래밍",
    alcSubTitle: "",
    alcOrganizer: "WISET_멀티캠퍼스",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://www.multicampus.com/kr/index.html",
    alcSite: "",
    alcGithub: "",
    alcBlog:
      "https://ddo0ii.notion.site/ddo0ii/Wiset-6c352eb74aab43129dcff5fa6bd0537a",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertai2.jpg?alt=media&token=67c1feb3-a03c-4051-ad83-4a25aef47c04",
    alcPrototype2:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertai1.jpg?alt=media&token=c57af034-a65e-4a01-975d-8c9274454757",
  },
  {
    id: 14,
    alcSImage:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertwiset1.jpg?alt=media&token=5bf77b01-a460-4808-b519-6b123aac4b30",
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[큐레이팅#]누구나 DO IT! 쉽게 시작하는 수익형 웹과 앱 만들기",
    alcSubTitle: "",
    alcOrganizer: "WISET_멀티캠퍼스",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://www.multicampus.com/kr/index.html",
    alcSite: "",
    alcGithub: "",
    alcBlog:
      "https://ddo0ii.notion.site/ddo0ii/Wiset-6c352eb74aab43129dcff5fa6bd0537a",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeVideo: "",
    alcPrototype1:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertwa2.jpg?alt=media&token=539c4542-a330-4b59-873e-c6e889ac69b1",
    alcPrototype2:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/alc%2Fcertificate%2Fcertwa1.jpg?alt=media&token=5f9eec09-b3b6-43b9-a792-08c5d3017b52",
  },
];

function ALC() {
  return (
    <Box
      sx={{
        pt: { sm: "50px", xs: "20px" },
        pb: { sm: "100px", xs: "80px" },
      }}
    >
      <Container>
        <TopTitle
          subTitle="QUALIFICATION"
          realTitle="AWARD & LICENSE & CERTIFICATE"
        />
        <Box>
          <ALCList alcList={alcData} />
        </Box>
      </Container>
    </Box>
  );
}

export default ALC;
