import React from "react";
import { Box, Container, Grid } from "@mui/material";
import TopTitle from "../components/TopTitle";
import ALCList from "../components/ALCList";

const alcData = [
  {
    id: 1,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faTrophy",
    alcTitle: "국경 없는 과학자 기술자 회장상",
    alcSubTitle: "제 10회 소외된 90%를 위한 창의설계 경진대회",
    alcOrganizer: "과학기술정보통신부",
    alcDate: "MAY 25, 2018",
    alcDeTitle1: "LANGUAGE & TOOL",
    alcDeContent1_1: "PWA",
    alcDeContent1_2: "Node.js",
    alcDeContent1_3: "MongoDB",
    alcDeContent1_4: "",
    alcDeTitle2: "INDUSTRY",
    alcDeContent2: "Developer 3",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "청각장애인은 물론 비장애인도 카페에서 음료 제조의 완료 알림을 받을 수 있고, 카페 매장 측은 마케팅 플랫폼으로 활용할 수 있는 시스템을 개발하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 2,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "정보처리기사",
    alcSubTitle: "한국산업인력공단",
    alcOrganizer: "",
    alcDate: "AUGUST 20, 2021",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 3,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "정보처리산업기사",
    alcSubTitle: "한국산업인력공단",
    alcOrganizer: "과학기술정보통신부",
    alcDate: "NOVEMBER 12, 2020",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 4,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "SQL 개발자(SQLD)",
    alcSubTitle: "데이터자격검정",
    alcOrganizer: "",
    alcDate: "JUNE 24, 2022",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 5,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "OPIc",
    alcSubTitle: "",
    alcOrganizer: "Intermediate Mid 2급",
    alcDate: "DECEMBER 28, 2019",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 6,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "컴퓨터활용능력 2급",
    alcSubTitle: "대한상공회의소",
    alcOrganizer: "과학기술정보통신부",
    alcDate: "AUGUST 2019",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 7,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "자동차 운전면허 1종 보통",
    alcSubTitle: "경찰청(운전면허시험관리단)",
    alcOrganizer: "",
    alcDate: "JANUARY 5, 2015",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 8,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "한입 크기로 잘라 먹는 리액트(React.js)",
    alcSubTitle: "Inflearn",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 9,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "트위터 클론코딩",
    alcSubTitle: "Nomad Coders",
    alcOrganizer: "과학기술정보통신부",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 10,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "ReactJS로 영화 웹 서비스 만들기",
    alcSubTitle: "Nomad Coders",
    alcOrganizer: "과학기술정보통신부",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 11,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[큐레이팅#]누구나 DO IT! 쉽게 시작하는 AI&프로그래밍",
    alcSubTitle: "WISET_멀티캠퍼스",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 12,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[큐레이팅#]누구나 DO IT! 쉽게 시작하는 수익형 웹과 앱 만들기",
    alcSubTitle: "WISET_멀티캠퍼스",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 13,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[직딩잇템]처음 시작하는 파이썬, 구조를 학습하라",
    alcSubTitle: "WISET_멀티캠퍼스",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 14,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[직딩잇템]처음 시작하는 파이썬, 문법부터 시작하라",
    alcSubTitle: "WISET_멀티캠퍼스",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "부동산계산기를 웹페이지에서도 모바일에서도 편리하게 사용할 수 있도록 깔끔한 디자인으로 기획하고 구상하여 제작하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
];

function ALC() {
  return (
    <Box
      sx={{
        pt: { sm: "50px", xs: "20px" },
        pb: { sm: "100px", xs: "80px" },
      }}
    >
      <Container>
        <TopTitle
          subTitle="QUALIFICATION"
          realTitle="AWARD & LICENSE & CERTIFICATE"
        />
        <ALCList alcList={alcData} />
      </Container>
    </Box>
  );
}

export default ALC;
