import React from "react";
import { Box, Container, Grid } from "@mui/material";
import TopTitle from "../components/TopTitle";
import ALCList from "../components/ALCList";

const alcData = [
  {
    id: 1,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faTrophy",
    alcTitle: "국경 없는 과학자 기술자 회장상",
    alcSubTitle: "제 10회 소외된 90%를 위한 창의설계 경진대회",
    alcOrganizer: "과학기술정보통신부",
    alcDate: "MAY 25, 2018",
    alcLecSite: "http://www.stiweb.org/",
    alcSite: "",
    alcGithub: "https://github.com/ddo0ii/capstone",
    alcBlog: "",
    alcYouTube: "https://youtu.be/5CEzAd3kDtg",
    alcDeTitle1: "LANGUAGE & TOOL",
    alcDeContent1_1: "PWA",
    alcDeContent1_2: "Node.js",
    alcDeContent1_3: "MongoDB",
    alcDeContent1_4: "",
    alcDeTitle2: "INDUSTRY",
    alcDeContent2: "Developer 3",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "청각장애인은 물론 비장애인도 카페에서 음료 제조의 완료 알림을 받을 수 있고, 카페 매장 측은 마케팅 플랫폼으로 활용할 수 있는 시스템을 개발하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 2,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "정보처리기사",
    alcSubTitle: "한국산업인력공단",
    alcOrganizer: "",
    alcDate: "AUGUST 20, 2021",
    alcLecSite: "https://www.hrdkorea.or.kr/",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 3,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "정보처리산업기사",
    alcSubTitle: "한국산업인력공단",
    alcOrganizer: "",
    alcDate: "NOVEMBER 12, 2020",
    alcLecSite: "https://www.hrdkorea.or.kr/",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 4,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "SQL 개발자(SQLD)",
    alcSubTitle: "데이터자격검정",
    alcOrganizer: "",
    alcDate: "JUNE 24, 2022",
    alcLecSite: "https://www.dataq.or.kr/www/main.do",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 5,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "OPIc",
    alcSubTitle: "MultiCampus",
    alcOrganizer: "Intermediate Mid 2급",
    alcDate: "DECEMBER 28, 2019",
    alcLecSite: "https://m.opic.or.kr/opics/jsp/senior/indexMobile.jsp",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 6,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "컴퓨터활용능력 2급",
    alcSubTitle: "대한상공회의소",
    alcOrganizer: "",
    alcDate: "AUGUST 2019",
    alcLecSite: "http://www.korcham.net/nCham/Service/Main/appl/Main.asp",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 7,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faIdCard",
    alcTitle: "자동차 운전면허 1종 보통",
    alcSubTitle: "경찰청(운전면허시험관리단)",
    alcOrganizer: "",
    alcDate: "JANUARY 5, 2015",
    alcLecSite: "https://www.safedriving.or.kr/main.do",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 8,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "한입 크기로 잘라 먹는 리액트",
    alcSubTitle: "Inflearn",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite:
      "https://www.inflearn.com/course/%ED%95%9C%EC%9E%85-%EB%A6%AC%EC%95%A1%ED%8A%B8/dashboard",
    alcSite: "",
    alcGithub:
      "https://github.com/ddo0ii/inflearn_react/tree/main/emotion-diary",
    alcBlog:
      "https://ddo-development.tistory.com/category/React/%ED%95%9C%EC%9E%85%20%ED%81%AC%EA%B8%B0%EB%A1%9C%20%EC%9E%98%EB%9D%BC%20%EB%A8%B9%EB%8A%94%20%EB%A6%AC%EC%95%A1%ED%8A%B8%28React.js%29",
    alcYouTube: "https://youtu.be/hE4qm1l6Da4",
    alcDeTitle1: "LANGUAGE & TOOL",
    alcDeContent1_1: "React.js",
    alcDeContent1_2: "JavaScript",
    alcDeContent1_3: "Node.js",
    alcDeContent1_4: "Firebase",
    alcDeTitle2: "TRAINING TIME",
    alcDeContent2: "16 Hours 57 Minutes",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "Inflearn의 <b>한입 크기로 잘라 먹는 리액트(React.js) : 기초부터 실전까지(https://www.inflearn.com/course/%ED%95%9C%EC%9E%85-%EB%A6%AC%EC%95%A1%ED%8A%B8#)</b>로 JavaScript와 React의 기초적인 개념을 Blog에 기록하며 학습하였다. 최종적으로 React.js를 이용하여 감정일기장을 제작하고 Firebase를 이용하여 프로젝트를 배포하였다.",
    alcPrototypeAlt: "",
    alcPrototype:
      "https://firebasestorage.googleapis.com/v0/b/portfolio-23686.appspot.com/o/project%2Fweb%2Fdiary%2Fdiary1_s.png?alt=media&token=16957c73-9239-4021-9b64-cb7cf4598cf2",
  },
  {
    id: 9,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "트위터 클론코딩",
    alcSubTitle: "Nomad Coders",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://nomadcoders.co/nwitter",
    alcSite: "https://ddo0ii.github.io/Twitter_React_NomadCoders",
    alcGithub: "https://github.com/ddo0ii/Twitter_React_NomadCoders",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "LANGUAGE & TOOL",
    alcDeContent1_1: "React.js",
    alcDeContent1_2: "JavaScript",
    alcDeContent1_3: "Node.js",
    alcDeContent1_4: "Firebase",
    alcDeTitle2: "TOOL",
    alcDeContent2:
      "Firebase, Cloud Firestore, NoSQL Realtime, Query, Filter, Firebase Authentication, Google Cloud Storage",
    alcDeTitle3: "FUNCTION",
    alcDeContent3:
      "Email, Google, Github, Social Authentication, Tweet CRUD, Protected Pages, Profile Page, File Upload, Deploy, API Key Security",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "Nomad Coders의 <b>트위터 클론코딩(https://nomadcoders.co/nwitter)</b>를 수강하였다. 최종적으로 React.js와 Firebase를 이용하여 백엔드 코딩없이 인증 및 리얼타임 DB를 구현하여 로그인, 트윗작성, 수정 삭제 등의 기본적인 트위터 웹 페이지를 제작하고 Github를 이용하여 프로젝트를 배포하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 10,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "ReactJS로 영화 웹 서비스 만들기",
    alcSubTitle: "Nomad Coders",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://nomadcoders.co/react-for-beginners",
    alcSite: "https://ddo0ii.github.io/NomadCoders_React",
    alcGithub:
      "https://github.com/ddo0ii/NomadCoders_React/tree/main/react-for-begginners",
    alcBlog:
      "https://ddo-development.tistory.com/category/React/ReactJS%EB%A1%9C%20%EC%98%81%ED%99%94%20%EC%9B%B9%20%EC%84%9C%EB%B9%84%EC%8A%A4%20%EB%A7%8C%EB%93%A4%EA%B8%B0",
    alcYouTube: "",
    alcDeTitle1: "LANGUAGE & TOOL",
    alcDeContent1_1: "React.js",
    alcDeContent1_2: "Node.js",
    alcDeContent1_3: "CSS",
    alcDeContent1_4: "",
    alcDeTitle2: "FUNCTION",
    alcDeContent2:
      "JSX, State, Props, Class Components, Data Fetching, Routing",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef:
      "Nomad Coders의 <b>ReactJS로 영화 웹 서비스 만들기(https://nomadcoders.co/react-for-beginners)</b>로 React의 기초적인 개념을 Blog에 기록하며 학습하였다. 최종적으로 React.js를 이용하여 영화 웹 서비스 페이지를 제작하고 Github를 이용하여 프로젝트를 배포하였다.",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 11,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[큐레이팅#]누구나 DO IT! 쉽게 시작하는 AI&프로그래밍",
    alcSubTitle: "WISET_멀티캠퍼스",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://www.multicampus.com/kr/index.html",
    alcSite: "",
    alcGithub: "",
    alcBlog: "",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 12,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[큐레이팅#]누구나 DO IT! 쉽게 시작하는 수익형 웹과 앱 만들기",
    alcSubTitle: "WISET_멀티캠퍼스",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://www.multicampus.com/kr/index.html",
    alcSite: "",
    alcGithub: "",
    alcBlog:
      "https://ddo0ii.notion.site/ddo0ii/Wiset-6c352eb74aab43129dcff5fa6bd0537a",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 13,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[직딩잇템]처음 시작하는 파이썬, 구조를 학습하라",
    alcSubTitle: "WISET_멀티캠퍼스",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://www.multicampus.com/kr/index.html",
    alcSite: "",
    alcGithub: "",
    alcBlog:
      "https://ddo0ii.notion.site/ddo0ii/Wiset-6c352eb74aab43129dcff5fa6bd0537a",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
  {
    id: 14,
    alcImage: "/images/projectImg/project1.jpg",
    alcIcon: "faMedal",
    alcTitle: "[직딩잇템]처음 시작하는 파이썬, 문법부터 시작하라",
    alcSubTitle: "WISET_멀티캠퍼스",
    alcOrganizer: "",
    alcDate: "DECEMBER 2019 - FEBRUARY 2020",
    alcLecSite: "https://www.multicampus.com/kr/index.html",
    alcSite: "",
    alcGithub: "",
    alcBlog:
      "https://ddo0ii.notion.site/ddo0ii/Wiset-6c352eb74aab43129dcff5fa6bd0537a",
    alcYouTube: "",
    alcDeTitle1: "",
    alcDeContent1_1: "",
    alcDeContent1_2: "",
    alcDeContent1_3: "",
    alcDeContent1_4: "",
    alcDeTitle2: "",
    alcDeContent2: "",
    alcDeTitle3: "",
    alcDeContent3: "",
    alcDeTitle4: "",
    alcDeContent4: "",
    alcDef: "",
    alcPrototypeAlt: "",
    alcPrototype: "/images/projectImg/project1_1.jpg",
  },
];

function ALC() {
  return (
    <Box
      sx={{
        pt: { sm: "50px", xs: "20px" },
        pb: { sm: "100px", xs: "80px" },
      }}
    >
      <Container>
        <TopTitle
          subTitle="QUALIFICATION"
          realTitle="AWARD & LICENSE & CERTIFICATE"
        />
        <ALCList alcList={alcData} />
      </Container>
    </Box>
  );
}

export default ALC;
